'use client'

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, Check, ChevronRight, Clock3, Cpu, CreditCard, IndianRupee, MapPin, Menu, MessageCircle, Moon, PackageCheck, Phone, Search, ShieldCheck, Smartphone, Sparkles, Star, Sun, TabletSmartphone, UserRound, Wrench, X, Zap, Bluetooth } from 'lucide-react'
import { adminRequest, discountPercent, mapsLink, Product, Service, Offer, Review, supabase, whatsappLink } from '@/lib/supabase'
import { ProductVisual } from '@/components/storefront/product-visual'
import { RepairForm } from '@/components/storefront/repair-form'
import { OwnerPanel } from '@/components/storefront/owner-panel'
import { ProductDetail } from '@/components/storefront/product-detail'
import { WhatsAppIcon } from '@/components/storefront/icons'

const whatsapp = '919981176713'
const iconMap: Record<string, typeof Wrench> = { Wrench, Cpu, ShieldCheck, Smartphone, Bluetooth, CreditCard, IndianRupee, PackageCheck, TabletSmartphone, Zap, Clock3, Sparkles }

export default function Page() {
  const [products, setProducts] = useState<Product[]>([]), [services, setServices] = useState<Service[]>([]), [offers, setOffers] = useState<Offer[]>([]), [reviews, setReviews] = useState<Review[]>([])
  const [query, setQuery] = useState(''), [brand, setBrand] = useState('सभी'), [category, setCategory] = useState('सभी'), [sort, setSort] = useState('new'), [dark, setDark] = useState(false), [menu, setMenu] = useState(false), [adminOpen, setAdminOpen] = useState(false), [authed, setAuthed] = useState(false), [passcode, setPasscode] = useState(''), [openId, setOpenId] = useState<string | null>(null)
  const pushed = useRef(false)
  const load = async () => { const [p, s, o, r] = await Promise.all([supabase.from('products').select('*').order('created_at'), supabase.from('services').select('*').order('sort_order'), supabase.from('offers').select('*').eq('active', true).order('created_at', { ascending: false }), supabase.from('reviews').select('*').eq('approved', true).order('created_at', { ascending: false })]); setProducts(p.data || []); setServices(s.data || []); setOffers(o.data || []); setReviews(r.data || []) }
  useEffect(() => { load(); const channel = supabase.channel('store-live').on('postgres_changes', { event: '*', schema: 'public' }, load).subscribe(); return () => { supabase.removeChannel(channel) } }, [])
  const brands = ['सभी', ...new Set(products.map(p => p.brand).filter(Boolean))]
  const categories = ['सभी', ...new Set(products.map(p => p.category || 'अन्य'))]
  const hasDiscount = products.some(product => discountPercent(product) > 0)
  const filtered = useMemo(() => {
    const list = products.filter(product => (category === 'सभी' || (product.category || 'अन्य') === category) && (brand === 'सभी' || product.brand === brand) && `${product.name} ${product.brand} ${product.category || ''}`.toLowerCase().includes(query.toLowerCase()))
    if (sort === 'low') return [...list].sort((a, b) => Number(a.price) - Number(b.price))
    if (sort === 'high') return [...list].sort((a, b) => Number(b.price) - Number(a.price))
    if (sort === 'off') return [...list].sort((a, b) => discountPercent(b) - discountPercent(a))
    return [...list].reverse()
  }, [products, category, brand, sort, query])
  const rating = reviews.length ? (reviews.reduce((a, r) => a + r.rating, 0) / reviews.length).toFixed(1) : '5.0'
  const openProduct = (id: string) => { pushed.current = true; window.history.pushState(null, '', `#p=${encodeURIComponent(id)}`); setOpenId(id) }
  const closeProduct = () => { if (pushed.current) { pushed.current = false; window.history.back() } else { window.history.replaceState(null, '', window.location.pathname + window.location.search); setOpenId(null) } }
  const current = openId ? products.find(p => p.id === openId) : undefined
  useEffect(() => { const sync = () => { const match = window.location.hash.match(/^#p=(.+)$/); setOpenId(match ? decodeURIComponent(match[1]) : null) }; sync(); window.addEventListener('popstate', sync); window.addEventListener('hashchange', sync); return () => { window.removeEventListener('popstate', sync); window.removeEventListener('hashchange', sync) } }, [])
  return <main className={dark ? 'site dark-mode' : 'site'}>
    <header className="nav-wrap"><nav className="nav container" aria-label="मुख्य नेविगेशन"><a href="#home" className="brand"><span className="brand-mark"><Smartphone size={20} /></span><span>Kamal <b>Mobile</b><small>& Video Graphy</small></span></a><div className={menu ? 'nav-links open' : 'nav-links'}><a href="#phones" onClick={() => setMenu(false)}>प्रोडक्ट्स</a><a href="#services" onClick={() => setMenu(false)}>सेवाएं</a><a href="#repair" onClick={() => setMenu(false)}>रिपेयर बुक करें</a><a href="#contact" onClick={() => setMenu(false)}>संपर्क</a></div><div className="nav-actions"><button className="icon-button" aria-label="थीम बदलें" onClick={() => setDark(!dark)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><a className="nav-call" href="tel:9981176713"><Phone size={16} /> कॉल करें</a><button className="menu-button" aria-label="मेनू" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div></nav></header>
    <section id="home" className="hero"><div className="hero-glow" /><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span /> आपका भरोसेमंद मोबाइल और एक्सेसरी स्टोर</div><h1>आपके मोबाइल की<br /><em>हर जरूरत का</em> समाधान।</h1><p>मोबाइल, headphones, headset, watch, accessories और digital services—सब कुछ एक ही जगह, आपके अपने दुल्लापुर बाजार में।</p><div className="hero-buttons"><a className="button primary" href={mapsLink} target="_blank" rel="noreferrer"><MapPin size={18} /> रास्ता देखें <ArrowUpRight size={16} /></a><a className="button ghost" href="tel:9981176713"><Phone size={17} /> अभी कॉल करें</a></div><div className="hero-stats"><div><b>10+</b><span>सालों का भरोसा</span></div><div><b>13</b><span>जरूरी सेवाएं</span></div><div><b>{rating}<span className="star">★</span></b><span>ग्राहक रेटिंग</span></div></div></div><div className="hero-card"><div className="hero-card-top"><span className="live-dot" /> आज की सुविधा</div><div className="phone-orbit"><div className="orbit-line" /><div className="phone-silhouette"><div className="phone-camera" /><div className="phone-screen"><Sparkles size={22} /><span>All brands<br />available</span></div></div></div><div className="hero-card-foot"><div><small>खुलने का समय</small><strong>सुबह 9:00 — रात 8:00</strong></div><Clock3 size={20} /></div></div></div></section>
    <section className="offers"><div className="container offer-inner"><div className="offer-label"><Sparkles size={18} /><div><b>आज के ऑफर</b><span>आपके लिए खास बचत</span></div></div>{offers.length ? offers.map(o => <div className="offer-empty" key={o.id}>{o.badge && <b>{o.badge} · </b>}{o.title} <span>{o.description}</span></div>) : <div className="offer-empty">इस समय कोई नया ऑफर नहीं है <span>जल्द वापस आएं!</span></div>}<ChevronRight size={18} className="offer-arrow" /></div></section>
    <section id="phones" className="section container"><div className="section-heading"><div><div className="eyebrow teal"><span /> नया और भरोसेमंद</div><h2>अपना अगला प्रोडक्ट <em>चुनें।</em></h2></div><a className="text-link" href="#contact">सभी मॉडल पूछें <ArrowUpRight size={16} /></a></div><div className="catalog-tools"><div className="search-box"><Search size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Product, category या brand खोजें..." aria-label="मॉडल या ब्रांड खोजें" /></div><div className="filters" aria-label="ब्रांड फिल्टर">{brands.map(b => <button key={b} className={brand === b ? 'filter active' : 'filter'} onClick={() => setBrand(b)}>{b}</button>)}</div></div>{categories.length > 2 && <div className="filters" aria-label="कैटेगरी फिल्टर">{categories.map(value => <button key={value} className={category === value ? 'filter active' : 'filter'} onClick={() => setCategory(value)}>{value}</button>)}</div>}<div className="sort-row"><label className="select-chip"><span>ब्रांड</span><select value={brand} onChange={event => setBrand(event.target.value)} aria-label="ब्रांड चुनें">{brands.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label className="select-chip"><span>क्रम</span><select value={sort} onChange={event => setSort(event.target.value)} aria-label="क्रम चुनें"><option value="new">नए पहले</option><option value="low">कीमत: कम से ज़्यादा</option><option value="high">कीमत: ज़्यादा से कम</option>{hasDiscount && <option value="off">सबसे ज़्यादा छूट</option>}</select></label><span className="result-count">{filtered.length} प्रोडक्ट</span></div><div className="product-grid">{filtered.map(p => <article className="product-card" key={p.id} onClick={event => { if (!(event.target as HTMLElement).closest('a,button')) openProduct(p.id) }}><ProductVisual product={p} /><div className="product-info"><div className="product-meta"><span>{p.brand}</span><span>{p.network}</span></div><h3><a href={`#p=${encodeURIComponent(p.id)}`} onClick={event => { event.preventDefault(); openProduct(p.id) }}>{p.name}</a></h3><p><span>{p.spec}</span><span className="price-line">{discountPercent(p) > 0 && <i className="off-pct">-{discountPercent(p)}%</i>}<b>₹{Number(p.price).toLocaleString('en-IN')}</b></span><span className="mrp-line">{discountPercent(p) > 0 && <>M.R.P.: <s>₹{Number(p.mrp).toLocaleString('en-IN')}</s></>}</span></p><a className="whatsapp-button" href={whatsappLink(`नमस्ते, मुझे ${p.name} (${p.spec}) के बारे में जानकारी चाहिए।`)} target="_blank" rel="noreferrer"><WhatsAppIcon size={17} /> WhatsApp पर पूछें</a></div></article>)}</div>{!filtered.length && <div className="offer-empty">अभी product सूची खाली है। Owner Panel से mobile, headphones, headset, watch या कोई भी product जोड़ें।</div>}</section>
    <section id="services" className="section services-section"><div className="container"><div className="section-heading"><div><div className="eyebrow teal"><span /> हमारे काम की खासियत</div><h2>हर जरूरत के लिए<br /><em>एक भरोसेमंद जगह।</em></h2></div></div><div className="service-grid">{services.map(s => { const Icon = iconMap[s.icon] || Wrench; return <article className="service-card" key={s.id}><div className="service-icon"><Icon size={21} /></div><h3>{s.title}</h3><p>{s.description}</p><ChevronRight className="service-arrow" size={18} /></article> })}</div></div></section>
    <section id="repair" className="repair-section"><div className="container repair-grid"><div className="repair-copy"><div className="eyebrow teal"><span /> परेशानी बताइए</div><h2>रिपेयर के लिए<br /><em>अपना स्लॉट बुक करें।</em></h2><p>फॉर्म भरते ही आपकी जानकारी WhatsApp पर भेजने के लिए तैयार हो जाएगी।</p><div className="repair-trust"><ShieldCheck size={19} /><span>आपकी जानकारी सुरक्षित रहेगी</span></div></div><RepairForm /></div></section>
    <section className="reviews section container"><div className="review-summary"><div className="eyebrow teal"><span /> ग्राहकों का भरोसा</div><h2>लोग क्या <em>कहते हैं?</em></h2><div className="rating"><strong>{rating}</strong><div><div className="stars">★★★★★</div><span>{reviews.length} ग्राहक रिव्यू</span></div></div></div><div className="review-cards">{reviews.slice(0, 2).map(r => <blockquote key={r.id}><div className="stars">{'★'.repeat(r.rating)}</div><p>“{r.comment}”</p><footer><span className="avatar">{r.customer_name.slice(0, 1)}</span><b>{r.customer_name}</b><small>{r.location || 'स्थानीय ग्राहक'}</small></footer></blockquote>)}</div></section>
    <footer id="contact" className="footer"><div className="container footer-grid"><div><a className="brand footer-brand" href="#home"><span className="brand-mark"><Smartphone size={20} /></span><span>Kamal <b>Mobile</b><small>& Video Graphy</small></span></a><p>आपके मोबाइल की हर जरूरत का समाधान।<br />दुल्लापुर बाजार में आपका स्वागत है।</p></div><div><h4>जल्दी जाएं</h4><a href="#phones">Products देखें</a><a href="#services">हमारी सेवाएं</a><a href="#repair">रिपेयर बुक करें</a></div><div><h4>संपर्क करें</h4><a href={mapsLink} target="_blank" rel="noreferrer"><MapPin size={15} /> मेन रोड, दुल्लापुर बाजार</a><a href="tel:9981176713"><Phone size={15} /> 99811 76713</a><span><Clock3 size={15} /> सुबह 9:00 से रात 8:00</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Kamal Mobile & Video Graphy. सर्वाधिकार सुरक्षित।</span><button className="owner-login" onClick={() => setAdminOpen(true)}><UserRound size={14} /> Owner Login</button></div></footer><a className="floating-wa" href={whatsappLink('नमस्ते Kamal Mobile, मुझे मदद चाहिए।')} target="_blank" rel="noreferrer" aria-label="WhatsApp पर संपर्क करें"><MessageCircle size={24} /></a>{adminOpen && <OwnerPanel onClose={() => setAdminOpen(false)} data={{ products, services, offers, reviews }} refresh={load} />}{current && <ProductDetail product={current} products={products} onClose={closeProduct} onOpen={openProduct} />}
  </main>
}


function OwnerPasscodePanel({ authed }: { authed: boolean }) { const [open, setOpen] = useState(false); const [currentPasscode, setCurrentPasscode] = useState(''); const [newPasscode, setNewPasscode] = useState(''); const [message, setMessage] = useState(''); if (!authed) return null; async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch('/api/owner', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'change_passcode', currentPasscode, newPasscode }) }); const result = await response.json(); setMessage(result.ok ? 'पासकोड सफलतापूर्वक बदल दिया गया।' : result.error === 'Current passcode is incorrect' ? 'पुराना पासकोड गलत है।' : 'पासकोड बदलने में समस्या हुई।'); if (result.ok) { setCurrentPasscode(''); setNewPasscode(''); } } return <section className={open ? 'owner-passcode open' : 'owner-passcode'}><button type='button' className='owner-passcode-toggle' onClick={() => setOpen(!open)}>पासकोड बदलें</button>{open && <form onSubmit={submit}><strong>Owner पासकोड बदलें</strong><input type='password' value={currentPasscode} onChange={event => setCurrentPasscode(event.target.value)} placeholder='पुराना पासकोड' required /><input type='password' value={newPasscode} onChange={event => setNewPasscode(event.target.value)} placeholder='नया पासकोड (कम से कम 4 अक्षर)' minLength={4} required /><button type='submit'>नया पासकोड सेव करें</button>{message && <small>{message}</small>}</form>}</section> }

function OwnerPhotoUploader({ passcode, authed }: { passcode: string; authed: boolean }) { const [urls, setUrls] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [newPasscode, setNewPasscode] = useState(''); const [message, setMessage] = useState(''); if (!authed) return null; async function upload(event: React.ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files || []).slice(0, 3); if (!files.length || !passcode) return; setBusy(true); const encoded = await Promise.all(files.map(file => new Promise<{ name: string; type: string; data: string }>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, type: file.type, data: String(reader.result) }); reader.onerror = reject; reader.readAsDataURL(file) }))); const response = await fetch('/api/owner', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-owner-passcode': passcode }, body: JSON.stringify({ action: 'upload_images', files: encoded }) }); const result = await response.json(); setUrls(result.urls || []); setBusy(false); } async function changePasscode(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (newPasscode.length < 4) { setMessage('नया पासकोड कम से कम 4 अक्षरों का रखें।'); return } const response = await fetch('/api/owner', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'change_passcode', currentPasscode: passcode, newPasscode }) }); const result = await response.json(); setMessage(result.ok ? 'पासकोड बदल दिया गया है। अगली बार नया पासकोड इस्तेमाल करें।' : 'पासकोड बदलने में समस्या हुई।'); if (result.ok) setNewPasscode(''); } return <div className="owner-upload"><strong>Product image चुनें (Gallery / Camera)</strong><label className="image-picker-button"><span>{busy ? 'अपलोड हो रहा है...' : 'Gallery से फोटो चुनें'}</span><input type="file" accept="image/*" multiple onChange={upload} disabled={busy || !passcode} /></label>{busy && <span>अपलोड हो रहा है...</span>}{urls.length > 0 && <div><p>पहला URL Image URL में और बाकी URLs Gallery URLs में paste करें:</p>{urls.map(url => <input key={url} readOnly value={url} onFocus={e => e.currentTarget.select()} />)}</div>}<form className="owner-passcode-form" onSubmit={changePasscode}><strong>Owner पासकोड बदलें</strong><input type="password" minLength={4} maxLength={32} value={newPasscode} onChange={e => setNewPasscode(e.target.value)} placeholder="नया पासकोड" required /><button className="button" type="submit">पासकोड बदलें</button>{message && <span>{message}</span>}</form></div> }

export { whatsapp }
